//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class kayit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kayit()
        {
            this.GunlukArsivs = new HashSet<GunlukArsiv>();
        }
    
        public int ID { get; set; }
        public string plaka { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<decimal> hasilat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GunlukArsiv> GunlukArsivs { get; set; }
    }
}
