//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusesDBEntities : DbContext
    {
        public BusesDBEntities()
            : base("name=BusesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_otobus> tbl_otobus { get; set; }
        public virtual DbSet<tbl_sefer> tbl_sefer { get; set; }
        public virtual DbSet<tbl_sehirler> tbl_sehirler { get; set; }
        public virtual DbSet<tbl_yolcu> tbl_yolcu { get; set; }
        public virtual DbSet<kayit> kayits { get; set; }
        public virtual DbSet<GunlukArsiv> GunlukArsivs { get; set; }
    }
}
