//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sehirler
    {
        public int SehirID { get; set; }
        public string SehirAdi { get; set; }
    }
}
