//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_yolcu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_yolcu()
        {
            this.tbl_sefer = new HashSet<tbl_sefer>();
        }
    
        public int YolcuID { get; set; }
        public string yolcuAdi { get; set; }
        public string yolcuSoyad { get; set; }
        public Nullable<int> otobusNo { get; set; }
        public string koltukNo { get; set; }
    
        public virtual tbl_otobus tbl_otobus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_sefer> tbl_sefer { get; set; }
    }
}
