//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sefer
    {
        public int seferID { get; set; }
        public Nullable<int> otobusID { get; set; }
        public Nullable<int> yolcuID { get; set; }
        public string seferKalkis { get; set; }
        public string seferVaris { get; set; }
        public Nullable<int> Tutar { get; set; }
    
        public virtual tbl_otobus tbl_otobus { get; set; }
        public virtual tbl_yolcu tbl_yolcu { get; set; }
    }
}
